info:
  name: get club notification settings
  type: http
  seq: 1

http:
  method: GET
  url: "{{host}}/club-notification-preferences/club/1"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
